Fix commit

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -54,20 +54,30 @@ jobs:
       uses: actions/checkout@v4
     - name: Run slim script for ${{ matrix.ontology }}
       run: bash src/build-workflow/slim.sh ${{ matrix.ontology }}
+    - name: Save slim output
+      run: |
+        mkdir -p slim-output
+        mv external-dev/${{ matrix.ontology }}.owl slim-output/
+      - name: Upload slim artifact
+      uses: actions/upload-artifact@v3
+      with:
+        name: slim-${{ matrix.ontology }}
+        path: slim-output/
 
   commit:
     needs: slim
     runs-on: ubuntu-latest
     steps:
-    - name: Commit OWL files
-      if: ${{ !startsWith(github.ref, 'refs/heads/merge') }}
+    - name: Download all slim artifacts
+      uses: actions/download-artifact@v3
+      with:
+        path: combined-slims
+    - name: Commit all OWL files
       run: |
         git config --local user.email "action@github.com"
         git config --local user.name "Slimmer bot"
         git checkout "${{ github.ref_name }}" && git pull
-        if ! git diff --quiet external-dev/*.owl; then
-          git add -f external-dev/*.owl
-          git commit -m "Actions - slim updated" || true
-          git push || echo "Push failed."
-        else
-          echo "No changes to commit or push."
+        mv combined-slims/* external-dev/
+        git add -f external-dev/*.owl
+        git commit -m "Actions - slim updated" || echo "No changes to commit."
+        git push || echo "Push failed."
